// enum about packet
package packets

// MQTT const value
const MQTT_PROTOCOL_NAME string = "MQTT"
const MQTT_PROTOCOL_LEVEL byte = 0x05

// MQTT Control Packet type
type MQTT_PACKET_TYPE byte

const (
	PACKET_TYPE_CONNECT     MQTT_PACKET_TYPE = 0x10
	PACKET_TYPE_CONNACK     MQTT_PACKET_TYPE = 0x20
	PACKET_TYPE_PUBLISH     MQTT_PACKET_TYPE = 0x30
	PACKET_TYPE_PUBACK      MQTT_PACKET_TYPE = 0x40
	PACKET_TYPE_PUBREC      MQTT_PACKET_TYPE = 0x50
	PACKET_TYPE_PUBREL      MQTT_PACKET_TYPE = 0x60
	PACKET_TYPE_PUBCOMP     MQTT_PACKET_TYPE = 0x70
	PACKET_TYPE_SUBSCRIBE   MQTT_PACKET_TYPE = 0x80
	PACKET_TYPE_SUBACK      MQTT_PACKET_TYPE = 0x90
	PACKET_TYPE_UNSUBSCRIBE MQTT_PACKET_TYPE = 0xA0
	PACKET_TYPE_UNSUBACK    MQTT_PACKET_TYPE = 0xB0
	PACKET_TYPE_PINGREQ     MQTT_PACKET_TYPE = 0xC0
	PACKET_TYPE_PINGRESP    MQTT_PACKET_TYPE = 0xD0
	PACKET_TYPE_DISCONNECT  MQTT_PACKET_TYPE = 0xE0
	PACKET_TYPE_AUTH        MQTT_PACKET_TYPE = 0xF0
)

// MQTT propertiyes key
type MQTT_PROPERTY_KEY byte

const (
	PROPERTY_PAYLOAD_FORMAT_INDICATOR          MQTT_PROPERTY_KEY = 0x01
	PROPERTY_MESSAGE_EXPIRY_INTERVAL           MQTT_PROPERTY_KEY = 0x02
	PROPERTY_CONTENT_TYPE                      MQTT_PROPERTY_KEY = 0x03
	PROPERTY_RESPONSE_TOPIC                    MQTT_PROPERTY_KEY = 0x08
	PROPERTY_CORRELATION_DATA                  MQTT_PROPERTY_KEY = 0x09
	PROPERTY_SUBSCRIPTION_IDENTIFIER           MQTT_PROPERTY_KEY = 0x0B
	PROPERTY_SESSION_EXPIRY_INTERVAL           MQTT_PROPERTY_KEY = 0x11
	PROPERTY_ASSIGNED_CLIENT_IDENTIFIER        MQTT_PROPERTY_KEY = 0x12
	PROPERTY_SERVER_KEEP_ALIVE                 MQTT_PROPERTY_KEY = 0x13
	PROPERTY_AUTHENTICATION_METHOD             MQTT_PROPERTY_KEY = 0x15
	PROPERTY_AUTHENTICATION_DATA               MQTT_PROPERTY_KEY = 0x16
	PROPERTY_REQUEST_PROBLEM_INFORMATION       MQTT_PROPERTY_KEY = 0x17
	PROPERTY_WILL_DELAY_INTERVAL               MQTT_PROPERTY_KEY = 0x18
	PROPERTY_REQUEST_RESPONSE_INFORMATION      MQTT_PROPERTY_KEY = 0x19
	PROPERTY_RESPONSE_INFORMATION              MQTT_PROPERTY_KEY = 0x1A
	PROPERTY_SERVER_REFERENCE                  MQTT_PROPERTY_KEY = 0x1C
	PROPERTY_REASON_STRING                     MQTT_PROPERTY_KEY = 0x1F
	PROPERTY_RECEIVE_MAXIMUM                   MQTT_PROPERTY_KEY = 0x21
	PROPERTY_TOPIC_ALIAS_MAXIMUM               MQTT_PROPERTY_KEY = 0x22
	PROPERTY_TOPIC_ALIAS                       MQTT_PROPERTY_KEY = 0x23
	PROPERTY_MAXIMUM_QOS                       MQTT_PROPERTY_KEY = 0x24
	PROPERTY_RETAIN_AVAILABLE                  MQTT_PROPERTY_KEY = 0x25
	PROPERTY_USER_PROPERTY                     MQTT_PROPERTY_KEY = 0x26
	PROPERTY_MAXIMUM_PACKET_SIZE               MQTT_PROPERTY_KEY = 0x27
	PROPERTY_WILDCARD_SUBSCRIPTION_AVAILABLE   MQTT_PROPERTY_KEY = 0x28
	PROPERTY_SUBSCRIPTION_IDENTIFIER_AVAILABLE MQTT_PROPERTY_KEY = 0x29
	PROPERTY_SHARED_SUBSCRIPTION_AVAILABLE     MQTT_PROPERTY_KEY = 0x2A
)
