// enum about packet
package packets

// MQTT const value
const MQTT_PROTOCOL_NAME string = "MQTT"
const MQTT_PROTOCOL_LEVEL byte = 0x05

// MQTT Control Packet type
type MQTT_PACKET_TYPE byte

const (
	PACKET_TYPE_CONNECT     MQTT_PACKET_TYPE = 0x10
	PACKET_TYPE_CONNACK     MQTT_PACKET_TYPE = 0x20
	PACKET_TYPE_PUBLISH     MQTT_PACKET_TYPE = 0x30
	PACKET_TYPE_PUBACK      MQTT_PACKET_TYPE = 0x40
	PACKET_TYPE_PUBREC      MQTT_PACKET_TYPE = 0x50
	PACKET_TYPE_PUBREL      MQTT_PACKET_TYPE = 0x60
	PACKET_TYPE_PUBCOMP     MQTT_PACKET_TYPE = 0x70
	PACKET_TYPE_SUBSCRIBE   MQTT_PACKET_TYPE = 0x80
	PACKET_TYPE_SUBACK      MQTT_PACKET_TYPE = 0x90
	PACKET_TYPE_UNSUBSCRIBE MQTT_PACKET_TYPE = 0xA0
	PACKET_TYPE_UNSUBACK    MQTT_PACKET_TYPE = 0xB0
	PACKET_TYPE_PINGREQ     MQTT_PACKET_TYPE = 0xC0
	PACKET_TYPE_PINGRESP    MQTT_PACKET_TYPE = 0xD0
	PACKET_TYPE_DISCONNECT  MQTT_PACKET_TYPE = 0xE0
	PACKET_TYPE_AUTH        MQTT_PACKET_TYPE = 0xF0
)

// MQTT propertiyes key
type MQTT_PROPERTY_KEY byte

const (
	PROPERTY_PAYLOAD_FORMAT_INDICATOR          MQTT_PROPERTY_KEY = 0x01
	PROPERTY_MESSAGE_EXPIRY_INTERVAL           MQTT_PROPERTY_KEY = 0x02
	PROPERTY_CONTENT_TYPE                      MQTT_PROPERTY_KEY = 0x03
	PROPERTY_RESPONSE_TOPIC                    MQTT_PROPERTY_KEY = 0x08
	PROPERTY_CORRELATION_DATA                  MQTT_PROPERTY_KEY = 0x09
	PROPERTY_SUBSCRIPTION_IDENTIFIER           MQTT_PROPERTY_KEY = 0x0B
	PROPERTY_SESSION_EXPIRY_INTERVAL           MQTT_PROPERTY_KEY = 0x11
	PROPERTY_ASSIGNED_CLIENT_IDENTIFIER        MQTT_PROPERTY_KEY = 0x12
	PROPERTY_SERVER_KEEP_ALIVE                 MQTT_PROPERTY_KEY = 0x13
	PROPERTY_AUTHENTICATION_METHOD             MQTT_PROPERTY_KEY = 0x15
	PROPERTY_AUTHENTICATION_DATA               MQTT_PROPERTY_KEY = 0x16
	PROPERTY_REQUEST_PROBLEM_INFORMATION       MQTT_PROPERTY_KEY = 0x17
	PROPERTY_WILL_DELAY_INTERVAL               MQTT_PROPERTY_KEY = 0x18
	PROPERTY_REQUEST_RESPONSE_INFORMATION      MQTT_PROPERTY_KEY = 0x19
	PROPERTY_RESPONSE_INFORMATION              MQTT_PROPERTY_KEY = 0x1A
	PROPERTY_SERVER_REFERENCE                  MQTT_PROPERTY_KEY = 0x1C
	PROPERTY_REASON_STRING                     MQTT_PROPERTY_KEY = 0x1F
	PROPERTY_RECEIVE_MAXIMUM                   MQTT_PROPERTY_KEY = 0x21
	PROPERTY_TOPIC_ALIAS_MAXIMUM               MQTT_PROPERTY_KEY = 0x22
	PROPERTY_TOPIC_ALIAS                       MQTT_PROPERTY_KEY = 0x23
	PROPERTY_MAXIMUM_QOS                       MQTT_PROPERTY_KEY = 0x24
	PROPERTY_RETAIN_AVAILABLE                  MQTT_PROPERTY_KEY = 0x25
	PROPERTY_USER_PROPERTY                     MQTT_PROPERTY_KEY = 0x26
	PROPERTY_MAXIMUM_PACKET_SIZE               MQTT_PROPERTY_KEY = 0x27
	PROPERTY_WILDCARD_SUBSCRIPTION_AVAILABLE   MQTT_PROPERTY_KEY = 0x28
	PROPERTY_SUBSCRIPTION_IDENTIFIER_AVAILABLE MQTT_PROPERTY_KEY = 0x29
	PROPERTY_SHARED_SUBSCRIPTION_AVAILABLE     MQTT_PROPERTY_KEY = 0x2A
)

type MQTT_REASON_CODE byte

const (
	RC_SUCCESS                                MQTT_REASON_CODE = 0x00
	RC_NORMAL                                 MQTT_REASON_CODE = 0x00
	RC_GRANTED_QOS_0                          MQTT_REASON_CODE = 0x00
	RC_GRANTED_QOS_1                          MQTT_REASON_CODE = 0x01
	RC_GRANTED_QOS_2                          MQTT_REASON_CODE = 0x02
	RC_DISCONNECT_WITH_WILL_MESSAGE           MQTT_REASON_CODE = 0x04
	RC_NO_MATCHING_SUBSCRIBERS                MQTT_REASON_CODE = 0x10
	RC_NO_SUBSCRIPTION_EXISTED                MQTT_REASON_CODE = 0x11
	RC_CONTINUE_AUTHENTICATION                MQTT_REASON_CODE = 0x18
	RC_RE_AUTHENTICATE                        MQTT_REASON_CODE = 0x19
	RC_UNSPECIFIED_ERROR                      MQTT_REASON_CODE = 0x80
	RC_MALFORMED_PACKET                       MQTT_REASON_CODE = 0x81
	RC_PROTOCOL_ERROR_CONNACK                 MQTT_REASON_CODE = 0x82
	RC_IMPLEMENTATION_SPECIFIC_ERROR          MQTT_REASON_CODE = 0x83
	RC_UNSUPPORTED_PROTOCOL_VERSION           MQTT_REASON_CODE = 0x84
	RC_CLIENT_IDENTIFIER_NOT_VALID            MQTT_REASON_CODE = 0x85
	RC_BAD_USER_NAME_OR_PASSWORD              MQTT_REASON_CODE = 0x86
	RC_NOT_AUTHORIZED                         MQTT_REASON_CODE = 0x87
	RC_SERVER_UNAVAILABLE                     MQTT_REASON_CODE = 0x88
	RC_SERVER_BUSY                            MQTT_REASON_CODE = 0x89
	RC_BANNED                                 MQTT_REASON_CODE = 0x8A
	RC_SERVER_SHUTTING_DOWN                   MQTT_REASON_CODE = 0x8B
	RC_BAD_AUTHENTICATION_METHOD              MQTT_REASON_CODE = 0x8C
	RC_KEEP_ALIVE_TIMEOUT                     MQTT_REASON_CODE = 0x8D
	RC_SESSION_TAKEN_OVER                     MQTT_REASON_CODE = 0x8E
	RC_TOPIC_FILTER_INVALID                   MQTT_REASON_CODE = 0x8F
	RC_TOPIC_NAME_INVALID                     MQTT_REASON_CODE = 0x90
	RC_PACKET_IDENTIFIER_IN_USE               MQTT_REASON_CODE = 0x91
	RC_PACKET_IDENTIFIER_NOT_FOUND            MQTT_REASON_CODE = 0x92
	RC_RECEIVE_MAXIMUM_EXCEEDED               MQTT_REASON_CODE = 0x93
	RC_TOPIC_ALIAS_INVALID                    MQTT_REASON_CODE = 0x94
	RC_PACKET_TOO_LARGE                       MQTT_REASON_CODE = 0x95
	RC_MESSAGE_RATE_TOO_HIGH                  MQTT_REASON_CODE = 0x96
	RC_QUOTA_EXCEEDED                         MQTT_REASON_CODE = 0x97
	RC_ADMINISTRATIVE_ACTION                  MQTT_REASON_CODE = 0x98
	RC_PAYLOAD_FORMAT_INVALID                 MQTT_REASON_CODE = 0x99
	RC_RETAIN_NOT_SUPPORTED                   MQTT_REASON_CODE = 0x9A
	RC_QOS_NOT_SUPPORTED                      MQTT_REASON_CODE = 0x9B
	RC_USE_ANOTHER_SERVER                     MQTT_REASON_CODE = 0x9C
	RC_SERVER_MOVED                           MQTT_REASON_CODE = 0x9D
	RC_SHARED_SUBSCRIPTIONS_NOT_SUPPORTED     MQTT_REASON_CODE = 0x9E
	RC_CONNECTION_RATE_EXCEEDED               MQTT_REASON_CODE = 0x9F
	RC_MAXIMUM_CONNECT_TIME                   MQTT_REASON_CODE = 0xA0
	RC_SUBSCRIPTION_IDENTIFIERS_NOT_SUPPORTED MQTT_REASON_CODE = 0xA1
	RC_WILDCARD_SUBSCRIPTIONS_NOT_SUPPORTED   MQTT_REASON_CODE = 0xA2
)
